use dioxus::prelude::*;

// Compile-time translation tables generated by `build.rs` from the
// externalized flat-JSON locale files (`i18n/en.json`, `i18n/zh-CN.json`).
// Each is a key-sorted `&'static [(&'static str, &'static str)]`, resolved at
// runtime with `binary_search_by` — no heap allocation, no runtime `HashMap`.
include!(concat!(env!("OUT_DIR"), "/i18n_tables.rs"));

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Language {
    En,
    ZhCn,
}

impl Language {
    pub fn code(&self) -> &'static str {
        match self {
            Language::En => "en",
            Language::ZhCn => "zh-CN",
        }
    }

    pub fn label(&self) -> &'static str {
        match self {
            Language::En => "English",
            Language::ZhCn => "\u{4e2d}\u{6587}",
        }
    }

    pub fn from_code(s: &str) -> Option<Self> {
        match s {
            "en" => Some(Language::En),
            "zh-CN" | "zh_CN" | "zh" => Some(Language::ZhCn),
            _ => None,
        }
    }

    pub fn all() -> &'static [Language] {
        &[Language::En, Language::ZhCn]
    }

    /// The compile-time translation table backing this language.
    fn table(&self) -> &'static [(&'static str, &'static str)] {
        match self {
            Language::En => I18N_EN,
            Language::ZhCn => I18N_ZH_CN,
        }
    }
}

impl std::hash::Hash for Language {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        core::mem::discriminant(self).hash(state);
    }
}

impl Eq for Language {}

/// Looks up `key` in the sorted static table for `lang`.
fn lookup(lang: Language, key: &str) -> Option<&'static str> {
    let table = lang.table();
    table
        .binary_search_by(|(k, _)| (*k).cmp(key))
        .ok()
        .map(|idx| table[idx].1)
}

static CURRENT_LANG: GlobalSignal<Language> = GlobalSignal::new(|| {
    crate::utils::storage::get_item("language")
        .and_then(|s| Language::from_code(&s))
        .unwrap_or(Language::En)
});

/// Translates `key` for the current language.
///
/// Resolution order is unchanged from the previous `HashMap`-backed
/// implementation: the current language first, then an `En` fallback, then the
/// key itself.
pub fn t(key: &str) -> String {
    let lang = *CURRENT_LANG.read();
    lookup(lang, key)
        .or_else(|| lookup(Language::En, key))
        .unwrap_or(key)
        .to_string()
}

pub fn set_language(lang: Language) {
    crate::utils::storage::set_item("language", lang.code());
    *CURRENT_LANG.write() = lang;
    apply_document_language(lang);
}

pub fn current_language() -> Language {
    *CURRENT_LANG.read()
}

pub fn sync_document_language() {
    let lang = crate::utils::storage::get_item("language")
        .and_then(|s| Language::from_code(&s))
        .unwrap_or(Language::En);
    apply_document_language(lang);
}

fn apply_document_language(lang: Language) {
    let Some(window) = web_sys::window() else {
        return;
    };
    let Some(document) = window.document() else {
        return;
    };
    let Some(root) = document.document_element() else {
        return;
    };
    let _ = root.set_attribute("lang", lang.code());
}
