use dioxus::prelude::*;
use yoface::dioxus_icons::lucide;

#[component]
pub fn Icon(name: String, #[props(default = "h-4 w-4".to_string())] class: String) -> Element {
    match name.as_str() {
        "activity" => rsx! { lucide::Activity { class: class.clone() } },
        "alert-triangle" | "triangle-alert" => {
            rsx! { lucide::TriangleAlert { class: class.clone() } }
        }
        "bell" => rsx! { lucide::Bell { class: class.clone() } },
        "briefcase" => rsx! { lucide::Briefcase { class: class.clone() } },
        "chevron-left" => rsx! { lucide::ChevronLeft { class: class.clone() } },
        "clock" => rsx! { lucide::Clock { class: class.clone() } },
        "code" => rsx! { lucide::Code { class: class.clone() } },
        "columns" => rsx! { lucide::Columns3 { class: class.clone() } },
        "credit-card" => rsx! { lucide::CreditCard { class: class.clone() } },
        "download" => rsx! { lucide::Download { class: class.clone() } },
        "edit" => rsx! { lucide::Pencil { class: class.clone() } },
        "file-lock" => rsx! { lucide::FileLock { class: class.clone() } },
        "file-text" => rsx! { lucide::FileText { class: class.clone() } },
        "fingerprint" => rsx! { lucide::FingerprintPattern { class: class.clone() } },
        "flag" => rsx! { lucide::Flag { class: class.clone() } },
        "gamepad-2" => rsx! { lucide::Gamepad2 { class: class.clone() } },
        "git-branch" => rsx! { lucide::GitBranch { class: class.clone() } },
        "globe" => rsx! { lucide::Globe { class: class.clone() } },
        "hash" => rsx! { lucide::Hash { class: class.clone() } },
        "heart-pulse" => rsx! { lucide::HeartPulse { class: class.clone() } },
        "image" => rsx! { lucide::Image { class: class.clone() } },
        "info" => rsx! { lucide::Info { class: class.clone() } },
        "key" => rsx! { lucide::KeyRound { class: class.clone() } },
        "layers" => rsx! { lucide::Layers { class: class.clone() } },
        "layout-dashboard" => rsx! { lucide::LayoutDashboard { class: class.clone() } },
        "link" => rsx! { lucide::Link { class: class.clone() } },
        "lock" => rsx! { lucide::Lock { class: class.clone() } },
        "log-out" => rsx! { lucide::LogOut { class: class.clone() } },
        "mail" => rsx! { lucide::Mail { class: class.clone() } },
        "megaphone" => rsx! { lucide::Megaphone { class: class.clone() } },
        "message-circle" => rsx! { lucide::MessageCircle { class: class.clone() } },
        "message-square" => rsx! { lucide::MessageSquare { class: class.clone() } },
        "monitor" => rsx! { lucide::Monitor { class: class.clone() } },
        "moon" => rsx! { lucide::Moon { class: class.clone() } },
        "plug" => rsx! { lucide::Plug { class: class.clone() } },
        "plus" => rsx! { lucide::Plus { class: class.clone() } },
        "refresh-cw" => rsx! { lucide::RefreshCw { class: class.clone() } },
        "scroll-text" => rsx! { lucide::ScrollText { class: class.clone() } },
        "search" => rsx! { lucide::Search { class: class.clone() } },
        "send" => rsx! { lucide::Send { class: class.clone() } },
        "server" => rsx! { lucide::Server { class: class.clone() } },
        "settings" => rsx! { lucide::Settings { class: class.clone() } },
        "shield" => rsx! { lucide::Shield { class: class.clone() } },
        "smartphone" => rsx! { lucide::Smartphone { class: class.clone() } },
        "sun" => rsx! { lucide::Sun { class: class.clone() } },
        "terminal" => rsx! { lucide::Terminal { class: class.clone() } },
        "ticket" => rsx! { lucide::Ticket { class: class.clone() } },
        "trash" => rsx! { lucide::Trash { class: class.clone() } },
        "upload" => rsx! { lucide::Upload { class: class.clone() } },
        "user" => rsx! { lucide::User { class: class.clone() } },
        "user-check" => rsx! { lucide::UserCheck { class: class.clone() } },
        "user-round" => rsx! { lucide::UserRound { class: class.clone() } },
        "users" => rsx! { lucide::Users { class: class.clone() } },
        "video" => rsx! { lucide::Video { class: class.clone() } },
        "webhook" => rsx! { lucide::Webhook { class: class.clone() } },
        "wrench" => rsx! { lucide::Wrench { class: class.clone() } },
        "x" => rsx! { lucide::X { class: class.clone() } },
        _ => rsx! { lucide::CircleQuestionMark { class: class.clone() } },
    }
}
